/* ============================================================
 * tools/hostcheck/stubs.c — пустые реализации символов Android,
 * AAudio и Vulkan для линковки на обычном Linux-хосте.
 *
 * Эти заглушки существуют ТОЛЬКО чтобы линковщик мог собрать
 * libnative-lib.so и доказать, что в нашем коде нет неразрешённых
 * символов. Результат неработоспособен и никогда не запускается.
 * Настоящие реализации приходят из Android NDK (см. build.sh).
 *
 * Сигнатуры намеренно упрощены до `long name(void)`: линковщику
 * важно только имя символа.
 * ============================================================ */
#include <stddef.h>

#define STUB(name) long name(void); long name(void) { return 0; }

/* ---- Vulkan ---- */
STUB(vkAcquireNextImageKHR)
STUB(vkAllocateCommandBuffers)
STUB(vkAllocateDescriptorSets)
STUB(vkAllocateMemory)
STUB(vkBeginCommandBuffer)
STUB(vkBindBufferMemory)
STUB(vkBindImageMemory)
STUB(vkCmdBeginRenderPass)
STUB(vkCmdBindDescriptorSets)
STUB(vkCmdBindIndexBuffer)
STUB(vkCmdBindPipeline)
STUB(vkCmdBindVertexBuffers)
STUB(vkCmdBlitImage)
STUB(vkCmdCopyBuffer)
STUB(vkCmdCopyBufferToImage)
STUB(vkCmdDraw)
STUB(vkCmdDrawIndexed)
STUB(vkCmdEndRenderPass)
STUB(vkCmdPipelineBarrier)
STUB(vkCmdPushConstants)
STUB(vkCmdSetScissor)
STUB(vkCmdSetViewport)
STUB(vkCreateAndroidSurfaceKHR)
STUB(vkCreateBuffer)
STUB(vkCreateCommandPool)
STUB(vkCreateDescriptorPool)
STUB(vkCreateDescriptorSetLayout)
STUB(vkCreateDevice)
STUB(vkCreateFence)
STUB(vkCreateFramebuffer)
STUB(vkCreateGraphicsPipelines)
STUB(vkCreateImage)
STUB(vkCreateImageView)
STUB(vkCreateInstance)
STUB(vkCreatePipelineLayout)
STUB(vkCreateRenderPass)
STUB(vkCreateSampler)
STUB(vkCreateSemaphore)
STUB(vkCreateShaderModule)
STUB(vkCreateSwapchainKHR)
STUB(vkDestroyBuffer)
STUB(vkDestroyCommandPool)
STUB(vkDestroyDescriptorPool)
STUB(vkDestroyDescriptorSetLayout)
STUB(vkDestroyDevice)
STUB(vkDestroyFence)
STUB(vkDestroyFramebuffer)
STUB(vkDestroyImage)
STUB(vkDestroyImageView)
STUB(vkDestroyInstance)
STUB(vkDestroyPipeline)
STUB(vkDestroyPipelineLayout)
STUB(vkDestroyRenderPass)
STUB(vkDestroySampler)
STUB(vkDestroySemaphore)
STUB(vkDestroyShaderModule)
STUB(vkDestroySurfaceKHR)
STUB(vkDestroySwapchainKHR)
STUB(vkDeviceWaitIdle)
STUB(vkEndCommandBuffer)
STUB(vkEnumerateDeviceExtensionProperties)
STUB(vkEnumerateInstanceExtensionProperties)
STUB(vkEnumerateInstanceLayerProperties)
STUB(vkEnumeratePhysicalDevices)
STUB(vkFreeCommandBuffers)
STUB(vkFreeMemory)
STUB(vkGetBufferMemoryRequirements)
STUB(vkGetDeviceQueue)
STUB(vkGetImageMemoryRequirements)
STUB(vkGetInstanceProcAddr)
STUB(vkGetPhysicalDeviceFormatProperties)
STUB(vkGetPhysicalDeviceMemoryProperties)
STUB(vkGetPhysicalDeviceProperties)
STUB(vkGetPhysicalDeviceQueueFamilyProperties)
STUB(vkGetPhysicalDeviceSurfaceCapabilitiesKHR)
STUB(vkGetPhysicalDeviceSurfaceFormatsKHR)
STUB(vkGetPhysicalDeviceSurfaceSupportKHR)
STUB(vkGetSwapchainImagesKHR)
STUB(vkMapMemory)
STUB(vkQueuePresentKHR)
STUB(vkQueueSubmit)
STUB(vkQueueWaitIdle)
STUB(vkResetCommandBuffer)
STUB(vkResetFences)
STUB(vkUnmapMemory)
STUB(vkUpdateDescriptorSets)
STUB(vkWaitForFences)

/* ---- Android NDK ---- */
STUB(__android_log_print)
STUB(__android_log_vprint)
STUB(__android_log_write)
STUB(ANativeWindow_getWidth)
STUB(ANativeWindow_getHeight)
STUB(ANativeWindow_getFormat)
STUB(ANativeWindow_acquire)
STUB(ANativeWindow_release)
STUB(ANativeWindow_setBuffersGeometry)
STUB(ANativeActivity_finish)
STUB(ANativeActivity_setWindowFlags)
STUB(AAssetManager_open)
STUB(AAsset_read)
STUB(AAsset_getLength)
STUB(AAsset_getLength64)
STUB(AAsset_getBuffer)
STUB(AAsset_close)
STUB(AInputEvent_getType)
STUB(AInputEvent_getSource)
STUB(AMotionEvent_getAxisValue)
STUB(AMotionEvent_getAction)
STUB(AMotionEvent_getPointerCount)
STUB(AMotionEvent_getPointerId)
STUB(AMotionEvent_getX)
STUB(AMotionEvent_getY)
STUB(AMotionEvent_getEventTime)
STUB(AKeyEvent_getAction)
STUB(AKeyEvent_getKeyCode)
STUB(ALooper_prepare)
STUB(ALooper_pollAll)
STUB(ALooper_pollOnce)
STUB(ALooper_addFd)

/* ---- AAudio ---- */
STUB(AAudio_createStreamBuilder)
STUB(AAudio_convertResultToText)
STUB(AAudioStreamBuilder_setSampleRate)
STUB(AAudioStreamBuilder_setChannelCount)
STUB(AAudioStreamBuilder_setFormat)
STUB(AAudioStreamBuilder_setDirection)
STUB(AAudioStreamBuilder_setPerformanceMode)
STUB(AAudioStreamBuilder_setDataCallback)
STUB(AAudioStreamBuilder_setErrorCallback)
STUB(AAudioStreamBuilder_openStream)
STUB(AAudioStreamBuilder_delete)
STUB(AAudioStream_requestStart)
STUB(AAudioStream_requestStop)
STUB(AAudioStream_close)
STUB(AAudioStream_getSampleRate)
STUB(AAudioStream_getChannelCount)
STUB(AAudioStream_getFramesPerBurst)

/* ---- android_native_app_glue ---- */
STUB(android_app_read_cmd)
STUB(android_app_pre_exec_cmd)
STUB(android_app_post_exec_cmd)
