# Оптимизация сборки
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Android
android.useAndroidX=false
android.enableJetifier=false
android.nonTransitiveRClass=true

# Native сборка
android.native.buildOutput=verbose

# Отключаем Lint в IDE
android.experimental.lint.version=8.2.2